# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grouping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grouping
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseStorage'
  pod 'SDWebImageSwiftUI'

end
